title: "test_multi"
no_cuda: False

task:
  datasets: ["fashion", "mnist"],
  in_size: [3, 32, 32]
  reset_targets: False
  validation: .8
  split: False
  perms_no: 3
  permute_targets: no

model:
  name: mlp
  hidden_units: [100]

elasticity:
  mode: ewc
  alpha: 0.25
  scale: 100
  g_norm: 2
  is_signed: False
  drop_misclassified: False
  loss_norm: 2
  do_sample: False
  signed_on_cpu: True

train:
  batch_size: 6000
  shuffle: True
  epochs_per_task: 5
  stop_if_not_better: 5
  test_batch_size: 0

  optimizer: Adam
  optimizer_args: { lr: 0.001 }

eval_freq: 1
save_freq: 1
