title: "test_multi"
no_cuda: False
mode: "ind"
keep_alive: yes

tasks:
  datasets: ["mnist"]
  in_size: [3, 32, 32]
  reset_targets: False
  validation: .2
  split: False
  perms_no: 0
  permute_targets: no

model:
  name: mlp
  hidden_units: [100, 100]
  use_softmax: no

elasticity:
  mode: ewc
  alpha: 0.25
  scale: 100
  g_norm: 2
  is_signed: False
  drop_misclassified: False
  loss_norm: 2
  do_sample: False
  signed_on_cpu: True

train:
  batch_size: 256
  shuffle: True
  epochs_per_task: 100
  stop_if_not_better: 5
  test_batch_size: 0
  optimizer: Adam
  optimizer_args: { lr: 0.001 }

reporting:
  eval_freq: 1
  save_report_freq: 5
  save_report_trace: yes
  batch_report_freq: 10
  epoch_report_freq: 1
  plot_tensorboard: no
  tensorboard_auto_start: yes
  plot_comet: no
  comet_plot_freq_factor: 0.1
