title: "multi_task"
no_cuda: False

datasets: ["cifar10", "fashion", "mnist"]
perms_no: 2
tasks_order: ["alt", "cifar10", "fashion", "mnist"]
up_size: []
permute_targets: yes
mode: seq
epochs_per_task: 10
stop_if_not_better: 5

train_batch_size: 64
test_batch_size: 0
optimizer: Adam
optimizer_args: { lr: 0.001 }

eval_freq: 1
save_freq: 10
