title: "andrei"
no_cuda: no
mode: "test_weight_importance"
keep_alive: no

tasks:
  datasets: ["cifar10"]
  in_size: [3, 32, 32]
  reset_targets: False
  validation: 0
  split: 1
  perms_no: 1
  permute_targets: no
  common_head: yes

model:
  name: mlp
  activation: &act "ReLU"
  _conv: [["Conv2d", -1, 20, 5], ["MaxPool2d", 2], [*act,],
          ["Conv2d", 20, 50, 5], ["MaxPool2d", 2], [*act,]]
  hidden_units: [100, 100]
  use_softmax: no

lifelong:
  mode: ewc
  scale: 100
  merge_elasticities: True
  first_task_only: False

  alpha: 0.25
  g_norm: 2
  is_signed: False
  drop_misclassified: False
  loss_norm: 2
  do_sample: False
  signed_on_cpu: True


train:
  batch_size: 1000
  shuffle: True
  epochs_per_task: 20
  max_nan_loss: 5
  stop_if_not_better: 3
  test_batch_size: 0
  _optimizer:
    name: Adam
    optimizer_args: { lr: 0.001 }

reporting:
  min_save: yes
  eval_freq: 1
  eval_not_trained: yes
  save_report_freq: 5
  save_report_trace: yes
  epoch_report_freq: 1

  batch_train_save_freq: 0
  batch_train_show_freq: 4
  batch_eval_save_freq: 0
  batch_eval_show_freq: 0

  plot_tensorboard: no
  tensorboard_auto_start: no
  plot_comet: no
  comet_plot_freq_factor: 0.1

  push_to_server: no
  generate_edata: no

test_weight_importance:
    variance_segments: ${eval, torch.arange(0, 0.2, 0.01)}
    no_samples: 10
