tasks:
  datasets: [["mnist", "fashion", "cifar10"], ["cifar10", "fashion", "mnist"]]

lifelong:
  scale: [0.1, 1, 3, 10, 30, 100, 300, 1000, 3000, 10000, 30000, 100000]
  merge_elasticities: [True, False]

model:
  name: [mlp, lenet]

train:
  _optimizer:
    - {"__name": "Adam 0.001", "name": Adam, "optimizer_args": {"lr": 0.001}}
    - {"__name": "RMSprop 0.001", "name": RMSprop, "optimizer_args": {"lr": 0.001}}
    - {"__name": "Adam 0.0001", "name": Adam, "optimizer_args": {"lr": 0.0001}}
    - {"__name": "RMSprop 0.0001", "name": RMSprop, "optimizer_args": {"lr": 0.0001}}
    - {"__name": "SGD 0.01 +M 0.95", "name": SGD, "optimizer_args": {"lr": 0.01, "momentum": 0.95}}
    - {"__name": "SGD 0.01 +M 0.95", "name": SGD, "optimizer_args": {"lr": 0.01, "momentum": 0.95}, "lr_decay": {"gamma": 0.1, "step": 5}}
    - {"__name": "SGD 0.1 +Nest 0.9 decay", "name": SGD, "optimizer_args": {"lr": 0.1, "nesterov": True, "momentum": 0.9}, "lr_decay": {"gamma": 0.1, "step": 5}}
